site_name: Jellyfin Enhanced
site_url: https://n00bcodr.github.io/Jellyfin-Enhanced/
repo_name: n00bcodr/Jellyfin-Enhanced
repo_url: https://github.com/n00bcodr/Jellyfin-Enhanced
site_description: The essential enhancement suite for Jellyfin, bundling advanced features and customizations into one convenient plugin.
site_author: n00bcodr
copyright: Copyright &copy; 2024-2026 n00bcodr

theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - announce.dismiss

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/n00bcodr/Jellyfin-Enhanced
      name: GitHub Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HKA2QNYJ6
      name: Jellyfin Community Discord - Jellyfin Enhanced Channel

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html


# main tabs/headers
nav:
  # ——————————————
  # landing page
  # ——————————————
  - Home: index.md


  # ——————————————
  # Installation
  # ——————————————
  - Installation: 
    - Standard (recommended): installation/standard-recommended.md
    - Platform-specific: installation/platform-specific.md


  # ——————————————
  # Enhanced
  # ——————————————
  - Enhanced::
    # Feature overview
    - Enhanced Features: enhanced/enhanced-features.md

    # Enhanced Settings
    - Enhanced Settings: enhanced/enhanced-settings.md


  # ——————————————
  # Elsewhere
  # ——————————————
  - Elsewhere:
    # Features overview
    - Elsewhere Features: elsewhere/elsewhere-features.md

    # Elsewhere Settings
    - Elsewhere Settings: elsewhere/elsewhere-settings.md


  # ——————————————
  # Jellyseerr
  # ——————————————
  - Jellyseerr:
    # Features overview
    - Jellyseerr Features: jellyseerr/jellyseerr-features.md

    # Jellyseerr Settings
    - Jellyserrr Settings: jellyseerr/jellyseerr-settings.md


  # ——————————————
  # *arr
  # ——————————————
  - "*arr":
    # Features overview
    - "*arr Features": arr/arr-features.md

    # *arr Settings
    - Other Settings: arr/arr-settings.md


  # ——————————————
  # Other
  # ——————————————
  - Other:
    # Features overview
    - Other Features: other/other-features.md

    # Other Settings
    - Other Settings: other/other-settings.md


  # ——————————————
  # Advanced, misc
  # ——————————————
  - Advanced: 
    - Configurations: advanced/configurations.md
    - Customization: advanced/customization.md
    - API: advanced/api.md
  - FAQ + Support: 
    - FAQ: faq-support/faq.md
    - Support: faq-support/support.md
  - Other Projects: other-projects/other-projects.md